# Generated by Django 2.1.3 on 2020-05-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, help_text='Enter contact email', max_length=254, null=True),
        ),
    ]
