# Generated by Django 2.1.3 on 2020-08-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, help_text='Enter contact email', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='authors',
            field=models.ManyToManyField(blank=True, null=True, to='matcher.Author'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='disciplines',
            field=models.ManyToManyField(blank=True, null=True, to='matcher.Discipline'),
        ),
        migrations.RemoveField(
            model_name='paper',
            name='languages',
        ),
        migrations.AddField(
            model_name='paper',
            name='languages',
            field=models.ManyToManyField(blank=True, null=True, to='matcher.Language'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='topics',
            field=models.ManyToManyField(blank=True, null=True, to='matcher.Topic'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
