# Generated by Django 2.1.3 on 2020-08-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0002_auto_20200812_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
