# Generated by Django 2.1.3 on 2020-05-31 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0002_auto_20200530_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='languages',
        ),
        migrations.AddField(
            model_name='paper',
            name='languages',
            field=models.ManyToManyField(to='matcher.Language'),
        ),
    ]
